spring:
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/produtos
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  application:
    name: produtos
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  instances:
    servico:
      baseConfig: default
server:
  port: 8080
